services:
  cassandra1:
    image: cassandra:4
    ports:
      - 7000:7000
      - 9042:9042
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
  cassandra2:
    image: cassandra:4
    ports:
      - 7001:7000
      - 9043:9042
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
  cassandra3:
    image: cassandra:4
    ports:
      - 7002:7000
      - 9044:9042
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
